/*
 * This file was auto-generated by speedy-antlr-tool v1.2.0
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "MyGrammarBaseVisitor.h"
#include "speedy_antlr.h"

class SA_MyGrammarTranslator : public MyGrammarBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *RootContext_cls = NULL;
    PyObject *BinaryExprContext_cls = NULL;
    PyObject *NOPContext_cls = NULL;
    PyObject *TernaryExprContext_cls = NULL;
    PyObject *LiteralContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *String_literalContext_cls = NULL;

    public:
    SA_MyGrammarTranslator(speedy_antlr::Translator *translator);
    ~SA_MyGrammarTranslator();
    antlrcpp::Any visitRoot(MyGrammarParser::RootContext *ctx);

    antlrcpp::Any visitBinaryExpr(MyGrammarParser::BinaryExprContext *ctx);

    antlrcpp::Any visitNOP(MyGrammarParser::NOPContext *ctx);

    antlrcpp::Any visitTernaryExpr(MyGrammarParser::TernaryExprContext *ctx);

    antlrcpp::Any visitLiteral(MyGrammarParser::LiteralContext *ctx);

    antlrcpp::Any visitNumber(MyGrammarParser::NumberContext *ctx);

    antlrcpp::Any visitString_literal(MyGrammarParser::String_literalContext *ctx);

};